web/Week_13/project/버전2_영화/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:movie_pk>/', views.detail, name='detail'),
    path('<int:movie_pk>/update/', views.update, name='update'),
    path('<int:movie_pk>/delete/', views.delete, name='delete'),
    path('<int:movie_pk>/create_comment/', views.create_comment, name='create_comment'),
    path('<int:movie_pk>/delete/<int:comment_pk>', views.delete_comment, name='delete_comment'),
]

web/Week_13/project/버전2_영화/movies/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Movie(models.Model):
    title = models.CharField(max_length=10)
    description = models.TextField()
    image  = models.ImageField(blank=True)

class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    content = models.CharField(max_length=100)

web/Week_13/project/버전2_영화/movies/forms.py
from django import forms
from .models import Movie, Comment

class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = '__all__'

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

web/Week_13/project/버전2_영화/movies/views.py
from django.shortcuts import render, redirect
from django.views.decorators.http import require_http_methods
from .models import Movie, Comment
from .forms import MovieForm, CommentForm

# Create your views here.
@require_http_methods(['GET'])
def index(request):
    movies = Movie.objects.all()
    context = {
        'movies': movies,
    }
    return render(request, 'movies/index.html', context)

@require_http_methods(['GET', 'POST'])
def create(request):
    if request.method == 'POST':
        form = MovieForm(request.POST, request.FILES)
        form.save()
        return redirect('movies:index')
    else:
        form = MovieForm()
    context = {
        'form': form,
    }
    return render(request, 'movies/create.html', context)

@require_http_methods(['GET'])
def detail(request, movie_pk):
    movie = Movie.objects.get(pk=movie_pk)
    comment_form = CommentForm()
    comments = movie.comment_set.all()
    context = {
        'movie': movie,
        'comment_form': comment_form,
        'comments': comments,
    }
    return render(request, 'movies/detail.html', context)

@require_http_methods(['GET', 'POST'])
def update(request, movie_pk):
    movie = Movie.objects.get(pk=movie_pk)
    if request.method == 'POST':
        form = MovieForm(request.POST, instance=movie)
        if form.is_valid():
            form.save()
            return redirect('movies:detail', movie.pk)
    else:
        form = MovieForm(instance=movie)
    context = {
        'movie': movie,
        'form': form,
    }
    return render(request, 'movies/update.html', context)

@require_http_methods(['POST'])
def delete(request, movie_pk):
    movie = Movie.objects.get(pk=movie_pk)
    movie.delete()
    return redirect('movies:index')

@require_http_methods(['POST'])
def create_comment(request, movie_pk):
    movie = Movie.objects.get(pk=movie_pk)
    comment_form = CommentForm(request.POST)
    comments = movie.comment_set.all()
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.user = request.user
        comment.movie = movie
        comment.save()
        return redirect('movies:detail', movie.pk)
    context = {
        'movie': movie,
        'comment_form': comment_form,
        'comments': comments,
    }
    return render(request, 'movies/detail.html', context)

@require_http_methods(['POST'])
def delete_comment(request, movie_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    if request.user == comment.user:
        comment.delete()
        return redirect('movies:detail', movie_pk)

web/Week_13/project/버전2_영화/movies/templates/movies/create.html
{% extends "base.html" %}

{% block title %}
Create
{% endblock title %}

{% block content %}
<h1>CREATE</h1>

<form action="{% url "movies:create" %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="제출">
</form>
{% endblock content %}

web/Week_13/project/버전2_영화/movies/templates/movies/detail.html
{% extends "base.html" %}

{% block title %}
{{ movie.title }}
{% endblock title %}

{% block content %}
<h1>DETAIL PAGE</h1>
{% if movie.image %}
<img src="{{ movie.image.url }}" alt="" style="width: 40%;">
{% endif %}

<h3>{{ movie.title }}</h3>
<p>{{ movie.description }}</p>
<hr>
<h4>댓글 등록</h4>
<form action="{% url "movies:create_comment" movie.pk %}" method="POST">
    {% csrf_token %}
    {{ comment_form.as_p}}
    <input type="submit" value="등록">
</form>
<hr>
<h4>댓글 목록</h4>
<ul>
    {% for comment in comments %}
        <li>{{ comment.user }} : {{ comment.content }}</li>
        {% if request.user == comment.user %}
            <form action="{% url "movies:delete_comment" movie.pk comment.pk %}" method="POST">
                {% csrf_token %}
                <input type="submit" value="삭제">
            </form>
        {% endif %}
    {% endfor %}
</ul>
<hr>
<a href="{% url "movies:update" movie.pk %}" class="btn btn-secondary">UPDATE</a>
<form action="{% url "movies:delete" movie.pk %}" method="POST" class="d-inline-block">
    {% csrf_token %}
    <input type="submit" value="DELETE" class="btn btn-danger">
</form>
<hr>
<a href="{% url "movies:index" %}" class="btn btn-primary">BACK</a>
{% endblock content %}

web/Week_13/project/버전2_영화/movies/templates/movies/index.html
{% extends "base.html" %}

{% block title %}
Index
{% endblock title %}

{% block content %}
<h1>INDEX PAGE</h1>

<article class="row gy-5">
  {% for movie in movies %}
  <div class="col-6">
    <div class="card h-100">
      <div class="card-header">{{ movie.title }}</div>
      <div class="card-body">
        <p class="card-text">{{ movie.description }}</p>
        <a href="{% url "movies:detail" movie.pk %}" class="btn btn-primary">Detail</a>
      </div>
    </div>
  </div>
  {% endfor %}
</article>  
{% endblock content %}

web/Week_13/project/버전2_영화/movies/templates/movies/update.html
{% extends "base.html" %}

{% block title %}
Update {{ movie.title}}
{% endblock title %}

{% block content %}
<h1>UPDATE</h1>

<form action="{% url "movies:update" movie.pk %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="제출">
</form>
{% endblock content %}