web/Week_13/project/버전2_영화/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('update/', views.update, name='update'),
    path('delete/', views.delete, name='delete'),
]

web/Week_13/project/버전2_영화/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    pass

web/Week_13/project/버전2_영화/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, UsernameField
from django.contrib.auth import get_user_model

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = ('username', 'email', 'first_name', 'last_name')

class CustomUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = ('email', 'first_name', 'last_name', 'username')

web/Week_13/project/버전2_영화/accounts/views.py
from django.shortcuts import render, redirect
from django.views.decorators.http import require_http_methods
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from .forms import CustomUserCreationForm, CustomUserChangeForm
from django.contrib.auth import update_session_auth_hash

# Create your views here.
@require_http_methods(['GET', 'POST'])
def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('movies:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)

@require_http_methods(['POST'])
def logout(request):
    if request.user.is_authenticated:
        auth_logout(request)
        return redirect('movies:index')
    
@require_http_methods(['GET', 'POST'])
def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('movies:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)

@require_http_methods(['GET', 'POST'])
def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
        return redirect('movies:index')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/update.html', context)

@require_http_methods(['POST'])
def delete(request):
    request.user.delete()
    return redirect('movies:index')

@require_http_methods(['GET', 'POST'])
def change_password(request, user_pk):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            return redirect('movies:index')
    else:
        form = PasswordChangeForm(request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/change_password.html', context)

web/Week_13/project/버전2_영화/accounts/templates/accounts/change_password.html
{% extends "base.html" %}

{% block title %}
Change Password
{% endblock title %}

{% block content %}
<h1>PASSWORD CHNAGE</h1>
<hr>
<form action="{% url "change_password" request.user.pk %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="비밀번호 변경">
</form>
{% endblock content %}

web/Week_13/project/버전2_영화/accounts/templates/accounts/login.html
{% extends "base.html" %}

{% block title %}
Login
{% endblock title %}

{% block content %}
<h1>LOGIN PAGE</h1>
<hr>
<form action="{% url "accounts:login" %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="로그인">
</form>
{% endblock content %}

web/Week_13/project/버전2_영화/accounts/templates/accounts/signup.html
{% extends "base.html" %}

{% block title %}
Signout
{% endblock title %}

{% block content %}
<h1>SIGNUP PAGE</h1>

<hr>
<form action="{% url "accounts:signup" %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="회원가입">
</form>
{% endblock content %}

web/Week_13/project/버전2_영화/accounts/templates/accounts/update.html
{% extends "base.html" %}

{% block title %}
Update {{ request.user }}
{% endblock title %}

{% block style %}
    #id_password, .helptext, form>p:nth-child(6) {
        display: none;
    }
{% endblock style %}

{% block content %}
<h1>UPDATE PAGE</h1>
<hr>
<form action="{% url "accounts:update" %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="수정">
</form>
<hr>
<form action="{% url "accounts:delete" %}" method="POST">
    {% csrf_token %}
    <input type="submit" value="회원탈퇴">
</form>
<form action="{% url "change_password" request.user.pk %}" method="POST">
    {% csrf_token %}
    <input type="submit" value="비밀번호 변경">
</form>
{% endblock content %}