web/Week_14/proejct/버전1_금융/mypjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('trends/', include('trends.urls'))
]

web/Week_14/proejct/버전1_금융/trends/urls.py
from django.urls import path
from . import views

app_name = 'trends'
urlpatterns = [
    path('keyword/', views.keyword, name='keyword'),
    path('keyword/<int:pk>/', views.keyword_detail, name='keyword_detail'),
    path('keyword/crawling/', views.crawling, name='crawling'),
    path('keyword/crawling/histogram/', views.crawling_histogram, name='crawling_histogram'),
    path('keyword/crawling/advanced/', views.crawling_advanced, name='crawling_advanced'),
]

web/Week_14/proejct/버전1_금융/trends/models.py
from django.db import models

# Create your models here.
class Keyword(models.Model):
    name = models.CharField(max_length=10)
    created_at = models.DateField(auto_now_add=True)

class Trend(models.Model):
    name = models.ForeignKey(Keyword, on_delete=models.CASCADE)
    result = models.IntegerField()
    search_period = models.TextField()
    created_at = models.DateField(auto_now_add=True)

web/Week_14/proejct/버전1_금융/trends/forms.py
from django import forms
from .models import Keyword

class KeywordForm(forms.ModelForm):
    class Meta:
        model = Keyword
        fields = '__all__'

web/Week_14/proejct/버전1_금융/trends/views.py
from django.shortcuts import render, redirect
from django.views.decorators.http import require_http_methods
from .models import Keyword, Trend
from .forms import KeywordForm

from bs4 import BeautifulSoup
from selenium import webdriver
import matplotlib.pyplot as plt
import base64
from io import BytesIO

# Create your views here.
@require_http_methods(['GET', 'POST'])
def keyword(request):
    keywords = Keyword.objects.all()
    if request.method == 'POST':
        form = KeywordForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('trends:keyword')
    else:
        form = KeywordForm()
    context = {
        'keywords': keywords,
        'form': form,
    }
    return render(request, 'trends/keyword.html', context)


@require_http_methods(['POST'])
def keyword_detail(request, pk):
    keyword = Keyword.objects.get(pk=pk)
    keyword.delete()
    return redirect('trends:keyword')


def get_data(keyword, option=False):
    if not option:
        url = f'https://www.google.com/search?q={keyword}'
    else:
        url = f'https://www.google.com/search?q={keyword}&tbs=qdr:y'

    driver = webdriver.Chrome()
    driver.get(url)

    html = driver.page_source
    soup = BeautifulSoup(html, 'html.parser')

    string = soup.select_one('div#result-stats').text
    start = end = 7
    for i in range(len(string) - 1, -1, -1):
        if string[i] == '개':
            end = i
            break
    return int("".join(string[start:end].split(',')))


@require_http_methods(['GET'])
def crawling(request):
    keywords = Keyword.objects.all()
    trends = Trend.objects.filter(search_period='all')
    for keyword in keywords:
        num = get_data(keyword.name)
        trend = Trend.objects.filter(search_period='all', name=keyword)
        if trend:
            trend.result = num
        else:
            trend = Trend(result=num, search_period='all', name=keyword)
            trend.save()
    
    context = {
        'trends': trends,
    }
    return render(request, 'trends/crawling.html', context)


def draw(option=False):
    if not option:
        trends = Trend.objects.filter(search_period='all')
    else:
        trends = Trend.objects.filter(search_period='year')

    plt.clf()
    x_values, y_values = [], []
    for trend in trends:
        x_values.append(trend.name.name)
        y_values.append(trend.result)

    plt.bar(x_values, y_values)
    plt.title('Technology Trend Analysis')
    plt.xticks(rotation=45)
    plt.xlabel('Keyword')
    plt.ylabel('Result')
    plt.grid(True)
    plt.legend(labels=['Trends'])

    buffer = BytesIO()
    plt.savefig(buffer, format='png')
    image_base64 = base64.b64encode(buffer.getvalue()).decode('utf-8').replace('\n', '')
    buffer.close()
    return image_base64


@require_http_methods(['GET'])
def crawling_histogram(request):
    context = {
        'bar_image': f'data:image/png;base64,{draw()}',
    }
    return render(request, 'trends/crawling_histogram.html', context)


@require_http_methods(['GET'])
def crawling_advanced(request):
    keywords = Keyword.objects.all()
    for keyword in keywords:
        num = get_data(keyword.name, option=True)
        trend = Trend.objects.filter(search_period='year', name=keyword)
        if trend:
            trend.result = num
        else:
            trend = Trend(result=num, search_period='year', name=keyword)
            trend.save()
    context = {
        'bar_image': f'data:image/png;base64,{draw(option=True)}',
    }
    return render(request, 'trends/crawling_advanced.html', context)

web/Week_14/proejct/버전1_금융/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
</head>
<body>
    <h1>트렌드 분석 애플리케이션</h1>
    <nav>
        <a href="{% url 'trends:keyword' %}">키워드 추가</a> |
        <a href="{% url 'trends:crawling' %}">크롤링</a> |
        <a href="{% url 'trends:crawling_histogram' %}">히스토그램</a> |
        <a href="{% url 'trends:crawling_advanced' %}">지난 1년 크롤링</a>
    </nav>
    {% block content %}{% endblock content %}
</body>
</html>

web/Week_14/proejct/버전1_금융/trends/templates/trends/crawling.html
{% extends "base.html" %}

{% block content %}
<h2>크롤링 기초 - 전체 기간 검색 결과</h2>
{% for trend in trends %}
    <p>검색결과: {{ trend.name.name }} - {{ trend.result }}개 / 검색일자: {{ trend.created_at|date:"Y-m-d" }}</p>
    <hr>
{% endfor %}
{% endblock content %}

web/Week_14/proejct/버전1_금융/trends/templates/trends/crawling_advanced.html
{% extends "base.html" %}

{% block content %}
<h2>지난 1년 간의 트렌드</h2>
<img src="{{ bar_image }}" alt="">
{% endblock content %}

web/Week_14/proejct/버전1_금융/trends/templates/trends/crawling_histogram.html
{% extends "base.html" %}

{% block content %}
<h2>전체 기간 검색 결과 히스토그램</h2>
<img src="{{ bar_image }}" alt="">
{% endblock content %}

web/Week_14/proejct/버전1_금융/trends/templates/trends/keyword.html
{% extends "base.html" %}

{% block content %}
<h2>키워드 추가</h2>
<form action="{% url 'trends:keyword' %}" method="POST">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="생성하기">
</form>
<hr>
<h3>분석을 원하는 키워드 목록</h3>
{% for keyword in keywords %}
    <p>{{ keyword.pk }}번째 키워드 - {{ keyword.name }}</p>
    <form action="{% url 'trends:keyword_detail' keyword.pk %}" method="POST">
        {% csrf_token %}
        <input type="submit" value="삭제하기">
    </form>
    <hr>
{% endfor %}
{% endblock content %}